version: '3.4'

services:
  backend:
    image: backend
    ports:
      - 80:80
    depends_on:
      - mysql
  mysql:
    image: 'mysql:5.7.22'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'

